modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
issueTrackerURL = "https://dc.mutils.net"

[[mods]]
modId = "veinminer"
version = "${version}"
displayName = "${name}"
displayURL = "https://modrinth.com/mod/veinminer"
logoFile = "assets/veinminer/icon.png"
authors = "${author}"
description = '''
${description}
'''

[[dependencies.veinminer]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.veinminer]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.veinminer]]
    modId = "klf"
    type = "required"
    versionRange = "[1,)"
    ordering = "NONE"
    side = "BOTH"

[[accessTransformers]]
    file = "META-INF/accesstransformer.cfg"
