modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
issueTrackerURL = "https://dc.mutils.net"

[[mods]]
modId = "veinminer-client"
version = "${version}"
displayName = "${name}"
displayURL = "https://modrinth.com/mod/veinminer-client"
logoFile = "assets/veinminer-client/icon.png"
authors = "${author}"
description = '''
${description}
'''

[[dependencies.veinminer-client]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.veinminer-client]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.veinminer-client]]
    modId = "kotlinforforge"
    type = "required"
    versionRange = "[5,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.veinminer-client]]
    modId = "veinminer"
    type = "required"
    versionRange = "[2.8.0,)"
    ordering = "AFTER"
    side = "BOTH"
